scaffold project + add crud task functions
DmitryBarskov/task-tracker pull request #26
Opened 2021-10-15 19:07 UTC by rav1ll

2021-10-21 10:22 UTC, DmitryBarskov requested changes

2021-10-21 10:22 UTC, DmitryBarskov commented on app/views/projects/_form.html.erb
> +
How do I see errors?

2021-10-21 10:22 UTC, DmitryBarskov commented on app/views/tasks/index.html.erb
> +          %>
A copy-paste

2021-10-21 10:22 UTC, DmitryBarskov commented on db/migrate/20210923114058_create_projects.rb
> +class CreateTasks < ActiveRecord::Migration[6.1]
You have to create another migration instead of changing an existing one.

2021-10-22 19:03 UTC, rav1ll commented on app/views/tasks/index.html.erb
> +          %>
сделал новый коммит с изменением обоих файлов, можно ли его здесь как-то указать?

2021-10-25 12:35 UTC, DmitryBarskov approved these changes
You shouldn't use scaffolding for tasks CRUD. -1

2021-10-25 12:35 UTC, closed without merging