Autor and reg
DmitryBarskov/task-tracker pull request #30
Opened 2021-10-20 10:56 UTC by Amir-Gaifullin

2021-10-26 14:36 UTC, DmitryBarskov requested changes
I don't see authorization here.

2021-10-26 14:36 UTC, DmitryBarskov commented on config/routes.rb
> +  get '/users', to: 'users#show'
You don't need this line, since it is already stated in the next one.

2021-10-26 14:36 UTC, DmitryBarskov commented on .semaphore/heroku.yml
> +version: v1.0
why do i see this file?

2021-10-26 14:36 UTC, DmitryBarskov commented on app/controllers/sessions_controller.rb
> +end
don't use tabs anymore.

2021-10-27 08:06 UTC, Amir-Gaifullin commented
@DmitryBarskov Now I have run this thread and I have authorization and registration here, do not understand the question?

2021-10-31 12:19 UTC, Amir-Gaifullin commented
This pr for authentication and registration, autorization in "Autorization_Task"

2021-10-31 17:31 UTC, DmitryBarskov approved these changes
LGFM

2021-10-31 17:31 UTC, closed without merging