Autorization_Task
DmitryBarskov/task-tracker pull request #33
Opened 2021-10-22 05:29 UTC by Amir-Gaifullin

2021-10-26 14:44 UTC, DmitryBarskov requested changes
I don't want to see changes unrelated to this PR

2021-10-26 14:44 UTC, DmitryBarskov commented on app/controllers/tasks_controller.rb
> +#   def create
What is it?

2021-10-27 07:53 UTC, Amir-Gaifullin commented
@DmitryBarskov не понял коментария, я же скопировал вашу ветку и внёс изменения авторизации для всех ресурсов
Ветка называется autor, потому-что я при копирование случайно ответвился с таким названием

2021-10-27 08:17 UTC, Amir-Gaifullin commented on app/controllers/tasks_controller.rb
> +#   def create
I forgot to remove this, i just split the old and new code this way. My bad(

2021-10-31 12:15 UTC, Amir-Gaifullin commented
Понял проблему, но решить её не могу. В следующих pr буду делать правильно.

2021-10-31 17:26 UTC, DmitryBarskov requested changes

2021-10-31 17:26 UTC, DmitryBarskov commented on db/migrate/20211020085832_add_user_to_task.rb
> +      table.integer :user_id, null: true
https://github.com/DmitryBarskov/task-tracker/pull/39/files#r739851192

2021-10-31 17:26 UTC, DmitryBarskov commented on app/views/tasks/index.html.slim
> +	 		td = task.description
Don't use tabs ever again

2021-10-31 17:26 UTC, DmitryBarskov commented on app/controllers/tasks_controller.rb
> +    raise Authorization::AuthorizationError, "You are not allowed to manage this task action"
You should use pundit everywhere.

2021-10-31 17:26 UTC, DmitryBarskov commented on app/controllers/projects_controller.rb
> +    raise Authorization::AuthorizationError, "You are not allowed to manage this project action"
Use pundit

2021-10-31 18:21 UTC, Amir-Gaifullin commented on app/views/tasks/index.html.slim
> +	 		td = task.description
![image](https://user-images.githubusercontent.com/47780452/139596675-c6081fd9-ffb6-4782-9e63-701fc212d0ca.png)

2021-10-31 18:50 UTC, Amir-Gaifullin commented on app/controllers/projects_controller.rb
> +    raise Authorization::AuthorizationError, "You are not allowed to manage this project action"
update

2021-10-31 18:50 UTC, Amir-Gaifullin commented on app/controllers/projects_controller.rb
> +    raise Authorization::AuthorizationError, "You are not allowed to manage this project action"
update

2021-10-31 18:50 UTC, Amir-Gaifullin commented on app/controllers/tasks_controller.rb
> +    raise Authorization::AuthorizationError, "You are not allowed to manage this task action"
update

2021-10-31 18:50 UTC, Amir-Gaifullin commented on db/migrate/20211020085832_add_user_to_task.rb
> +      table.integer :user_id, null: true
update

2021-10-31 18:54 UTC, Amir-Gaifullin commented
ahhahahahhahaha +18k change, I forgot add webpacker in .gitignore

2021-10-31 18:55 UTC, Amir-Gaifullin commented
Should I remake the comit?

2021-11-01 08:16 UTC, DmitryBarskov commented on db/migrate/20211020085832_add_user_to_task.rb
> +      table.integer :user_id, null: true
Что-то ничего не изменилось

2021-11-01 08:20 UTC, Amir-Gaifullin commented on db/migrate/20211020085832_add_user_to_task.rb
> +      table.integer :user_id, null: true
add_column :tasks, :user_id, :integer, null: true

2021-11-01 08:20 UTC, Amir-Gaifullin commented on db/migrate/20211020085832_add_user_to_task.rb
> +      table.integer :user_id, null: true
ты про это имеешь ввиду?

2021-11-01 08:21 UTC, Amir-Gaifullin commented on db/migrate/20211020085832_add_user_to_task.rb
> +      table.integer :user_id, null: true
@DmitryBarskov

2021-11-01 08:32 UTC, Amir-Gaifullin commented on db/migrate/20211020085832_add_user_to_task.rb
> +      table.integer :user_id, null: true
```class AddUserToTask < ActiveRecord::Migration[6.1]
  def change
    add_column :tasks, :user_id, :integer, null: true
  end
end```

2022-01-25 14:54 UTC, closed without merging