add_simple_tests
DmitryBarskov/task-tracker pull request #39
Opened 2021-10-31 11:43 UTC by Amir-Gaifullin

2021-10-31 17:19 UTC, DmitryBarskov requested changes

2021-10-31 17:19 UTC, DmitryBarskov commented on app/controllers/sessions_controller.rb
> +      @user.errors.add :base, "Wrong emails or password"
Don't change this line

2021-10-31 17:19 UTC, DmitryBarskov commented on app/controllers/sessions_controller.rb
> +
Don't change this line

2021-10-31 17:19 UTC, DmitryBarskov commented on app/controllers/tasks_controller.rb
> +  # before_action :authorize!, only: %i[edit update destroy]
Don't commit commented code

2021-10-31 17:19 UTC, DmitryBarskov commented on app/controllers/tasks_controller.rb
> +    @task = Task.find(params[:id])
Use `find_by!` so that you can handle ActiveRecord::RecordNotFound error

2021-10-31 17:19 UTC, DmitryBarskov commented on app/controllers/tasks_controller.rb
> +    params.require(:task).permit(:project_id, :title, :description, :deadline_at).merge(user_id: current_user.id)
Just a note - you can use just `user` here
```suggestion
    params.require(:task).permit(:project_id, :title, :description, :deadline_at).merge(user: current_user)
```

2021-10-31 17:19 UTC, DmitryBarskov commented on db/migrate/20211014131425_add_user_to_task.rb
> +      table.integer :user_id, null: true
It should be a reference instead of just a number. See other migration files to see how relations are implemented.

2021-10-31 17:19 UTC, DmitryBarskov commented on spec/factories/tasks.rb
> +    sequence(:project){"Project #"}
This won't work since project is not a string

2021-10-31 17:19 UTC, DmitryBarskov commented on spec/factories/tasks.rb
> +    sequence(:title) {"Task #" }
To use a sequence you should give a block with 1 argument - the number from the sequence
```ruby
sequence(:title) { |n| "Task ##{n}" } # will produce "Task #1", "Task #2" and so on.
```

2021-10-31 17:19 UTC, DmitryBarskov commented on spec/features/tasks/delete_spec.rb
> +    expect(page).to have_no_content('A test task!!!!!!!!!')
You should also check that you've been redirected to some specific page and you can see a message stating that the task was deleted.

2021-10-31 17:19 UTC, DmitryBarskov commented on spec/features/tasks/delete_spec.rb
> +    save_and_open_page
This is for debugging purposes only.

2021-10-31 17:19 UTC, DmitryBarskov commented on spec/features/tasks/delete_spec.rb
> +    end
This test is completely wrong - if something is broken it won't tell you. You should perform some actions before assertions

2021-10-31 17:19 UTC, DmitryBarskov commented on spec/features/tasks/edit_spec.rb
> +    fill_in Description, with: 'Another description'
So you even didn't run the tests? It won't even start

2021-10-31 17:19 UTC, DmitryBarskov commented on spec/factories/tasks.rb
> +    deadline_at {2.days.since}
Since what? Use `from_now` instead for better readability.

2021-10-31 17:19 UTC, DmitryBarskov commented on spec/features/tasks/view_spec.rb
> +  let(:task) { create(:task, project: project, title: 'A test task!!!!!!!!!', user_id: current_user) }
You don't need to specify a project here.

2021-10-31 17:27 UTC, Amir-Gaifullin commented on spec/features/tasks/delete_spec.rb
> +    save_and_open_page
да я это уже понял,мне просто удобно было смотреть страницу на которую он переходил

2021-10-31 17:29 UTC, DmitryBarskov commented on spec/features/tasks/delete_spec.rb
> +    save_and_open_page
нужно удалять все подобные строки перед созданием коммита

2021-11-01 11:16 UTC, Amir-Gaifullin commented
Update tests

2021-11-15 17:50 UTC, DmitryBarskov requested changes
You should address all the comments before requesting review again

2021-11-15 17:50 UTC, DmitryBarskov commented on db/migrate/20211014131420_add_user_to_project.rb
> +    add_column :projects, :user_id, :integer, null: true
You should use `reference` 

Example:
```ruby
add_reference :uploads, :user, index: true
```

2021-11-15 17:50 UTC, DmitryBarskov commented on spec/features/projects/edit_spec.rb
> +    save_and_open_page
Remove this line.

2021-11-18 16:11 UTC, DmitryBarskov approved these changes

2021-11-18 16:12 UTC, closed without merging