Auth for tasks & users
DmitryBarskov/task-tracker pull request #45
Opened 2021-11-14 15:29 UTC by Ramazan2002

2021-11-14 19:55 UTC, DmitryBarskov commented on app/policies/task_policy.rb
> +class TaskPolicy < ApplicationPolicy
How did you create this file?

2021-11-14 20:41 UTC, Ramazan2002 commented on app/policies/task_policy.rb
> +class TaskPolicy < ApplicationPolicy
Я делал по аналогии с проектами

2021-11-15 12:26 UTC, DmitryBarskov requested changes

2021-11-15 12:26 UTC, DmitryBarskov commented on app/policies/task_policy.rb
> +class TaskPolicy < ApplicationPolicy
So it's wrong

2021-11-15 19:14 UTC, closed without merging