tests
DmitryBarskov/task-tracker pull request #46
Opened 2021-11-14 19:28 UTC by Ramazan2002

2021-11-14 19:52 UTC, DmitryBarskov requested changes

2021-11-14 19:52 UTC, DmitryBarskov commented on db/migrate/20210923132042_create_tasks.rb
> +      t.references :user, null: false, foreign_key: true
Where is the migration file?

2021-11-14 19:52 UTC, DmitryBarskov commented on spec/policies/task_policy_spec.rb
> +  let(:task) {Task.new}
Why do you need it here? This variable seems to be unused.

2021-11-14 19:52 UTC, DmitryBarskov commented on spec/policies/task_policy_spec.rb
> +    let(:project) { Project.new(id: 1, user: creator) }
Why do you think the project need an ID?

2021-11-14 20:42 UTC, Ramazan2002 commented on db/migrate/20210923132042_create_tasks.rb
> +      t.references :user, null: false, foreign_key: true
Я просто не включил его в коммит. Сейчас прикреплю

2021-11-15 08:44 UTC, DmitryBarskov requested changes

2021-11-15 08:44 UTC, DmitryBarskov commented on db/migrate/20211114191403_add_user_to_task.rb
> +      table.index :user_id
you should add contstraints.

2021-11-15 08:44 UTC, DmitryBarskov commented on spec/features/tasks/delete_spec.rb
> +RSpec.describe 'Delete task', type: :feature do
Rewrite this file from scratch. You must not copy some other code.

2022-01-25 14:54 UTC, closed without merging