Refactoring
DmitryBarskov/task-tracker pull request #51
Opened 2021-11-18 18:05 UTC by Pumpka-s

Check this PR: https://github.com/Pumpka-s/task-tracker/pull/6

2021-11-24 10:11 UTC, DmitryBarskov requested changes

2021-11-24 10:11 UTC, DmitryBarskov commented on app/controllers/comments_controller.rb
> +      redirect_to @comment.task, alert: @comment.errors.first.full_message
You should just do `render :edit`

2021-11-24 10:11 UTC, DmitryBarskov commented on app/views/comments/_form.html.slim
> +  = render '/common/errors', model: comment
If you use simple_form the errors are shown without this line

2021-11-24 17:38 UTC, Pumpka-s commented on app/controllers/comments_controller.rb
> +      redirect_to @comment.task, alert: @comment.errors.first.full_message
Fixed

2021-11-24 17:38 UTC, Pumpka-s commented on app/views/comments/_form.html.slim
> +  = render '/common/errors', model: comment
Fixed

2021-11-26 14:22 UTC, DmitryBarskov approved these changes

2021-11-26 14:22 UTC, closed without merging