Graphql basics
DmitryBarskov/task-tracker pull request #63
Opened 2021-11-29 20:20 UTC by Ramazan2002

2021-11-29 20:27 UTC, Ramazan2002 commented
@DmitryBarskov @KilinMikhail

2021-12-13 12:40 UTC, DmitryBarskov requested changes

2021-12-13 12:40 UTC, DmitryBarskov commented on app/controllers/comments_controller.rb
> +          task: @task
At the same time you accept `task_id` and infer `task`. Could you remove some of them?

2021-12-13 12:40 UTC, DmitryBarskov commented on app/views/task_mailer/task_created.text.slim
> +| New product #{@task.name} created. You is a member of this product
???

2021-12-13 12:40 UTC, DmitryBarskov commented on app/views/task_mailer/task_created.html.slim
> +  | New product #{@task.name} created.
what is product?

2021-12-14 15:59 UTC, DmitryBarskov approved these changes

2021-12-14 15:59 UTC, closed without merging